on:
  workflow_call:

jobs:
  build:
    name: Check source code and emit build artifacts to dist/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set pnpm latest
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint

      - name: Format source
        run: pnpm format

      - name: Run unit tests
        run: pnpm test

      - name: Run build
        run: pnpm build

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          message: 'chore: [skip-ci] formatted code & build artifacts'
          add: '.'
