on:
  workflow_call:

jobs:
  e2e:
    name: Run action on a real agent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          milliseconds: 1000
