name: 'Continuous Integration'
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/build.yml

  analyze_source:
    uses: ./.github/workflows/analyze.yml

  e2e:
    needs: [build, analyze_source]
    uses: ./.github/workflows/e2e.yml
